/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brainbg_ndkfirst_JNIUtils */

#ifndef _Included_com_brainbg_ndkfirst_JNIUtils
#define _Included_com_brainbg_ndkfirst_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brainbg_ndkfirst_JNIUtils
 * Method:    getDataFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_brainbg_ndkfirst_JNIUtils_getDataFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_brainbg_ndkfirst_JNIUtils
 * Method:    getDataFromCPP
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_brainbg_ndkfirst_JNIUtils_getDataFromCPP
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
